// <auto-generated />
namespace SportNutr.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Nikita : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nikita));
        
        string IMigrationMetadata.Id
        {
            get { return "202404091844551_Nikita"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
